### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by titaniumrain** [luost26/diffusion-point-cloud#12]
Hi folks,

when training the model with "Car" shapes, the process is halted because of the following error

Pairwise EMD-CD:   9%|########6                                                                                       | 36/400 [00:00<00:03, 97.56it/s]
Traceback (most recent call last):
  File "train_gen.py", line 218, in <module>
    test(it)
  File "train_gen.py", line 185, in test
    results = compute_all_metrics(gen_pcs.to(args.device), ref_pcs.to(args.device), args.val_batch_size, accelerated_cd=True)
  File "/pointcloudsgan/code/diffusion-point-cloud/evaluation/evaluation_metrics.py", line 196, in compute_all_metrics
    ref_pcs, sample_pcs, batch_size, accelerated_cd=accelerated_cd)
  File "/pointcloudsgan/code/diffusion-point-cloud/evaluation/evaluation_metrics.py", line 110, in _pairwise_EMD_CD_
    emd_batch = emd_approx(sample_batch_exp, ref_batch)
  File "/pointcloudsgan/code/diffusion-point-cloud/evaluation/evaluation_metrics.py", line 21, in emd_approx
    emd = match_cost(sample, ref)  # (B,)
  File "/pointcloudsgan/code/diffusion-point-cloud/evaluation/StructuralLosses/match_cost.py", line 22, in forward
    cost = MatchCost(seta, setb, match)
RuntimeError: CUDA kernel failed : 700

It is quite strange since we use the pretrained model to test airplane/chair generation and don't have any problems using Pairwise EMD-CD. Any insights?

Our GPU is RTX 6000 with CUDA 11.0. StructuralLoss was also correctly compiled. 

Many thanks in advance.

**Comment by InfyIT-fa** [comment]
Hi, I have a quick question, did you able to build StructuralLossesBacken ? If yes, then would you please let me know how ? I am getting a g++ error ( created an issues already but no response yet).

**Comment by titaniumrain** [comment]
it is pretty straightfoward to compile StructuralLosses. A couple of things you need to change based up on my experience 

1. the path to nvcc
2. output folder of the compiled .so

Otherwise, it should be fine.

**Comment by luost26** [comment]
Hi all,

EMD_CD functions are for validation purpose only. The training doesn't rely on them, so you may remove this part of codes in the training script. I will also release a version without them later.

**Comment by titaniumrain** [comment]
Thanks Luo! Thats' what I end up doing :) Again, much appreciated for your time to get back to me.
